version: 1
disable_existing_loggers: false
formatters:
  standard:
    format: '%(asctime)s [%(levelname)s] [%(threadName)s] %(message)s'
handlers:
  default:
    level: 20  # Numeric value for logging.INFO
    formatter: standard
    class: logging.StreamHandler
  thread_file_handler:
    level: 20  # Numeric value for logging.INFO
    formatter: standard
    class: logging.FileHandler
    filename: ''
loggers:
  '':
    handlers:
      - default
      - thread_file_handler
    level: 20  # Numeric value for logging.INFO
    propagate: true

